# Generated by Django 6.1.1 on 2026-10-09 04:37

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), name='inv_category_name_ci_uniq'), models.CheckConstraint(condition=django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim('name')), 0), name='inv_category_name_nonblank')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='equipment_types', to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_identifier', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On_Loan', 'On loan'), ('Under_Maintenance', 'Under maintenance'), ('Retired', 'Retired')], default='Available', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('equipment_type', models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='inventory.equipmenttype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='equipmenttype',
            constraint=models.UniqueConstraint(models.F('category'), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), name='inv_type_cat_name_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='equipmenttype',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim('name')), 0), name='inv_type_name_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('asset_identifier')), name='inv_asset_ident_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim('asset_identifier')), 0), name='inv_asset_identifier_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length(django.db.models.functions.text.Trim('name')), 0), name='inv_asset_name_nonblank'),
        ),
    ]
