# Generated by Django 6.1.1 on 2026-09-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = ()

    operations = (
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=500)),
            ],
        ),
    )
